### ISSUE TITLE
App crash when trying to rescan media player.

### ISSUE THREAD

**Issue by dzami** [souch/SMP#42]
EXPECTED BEHAVIOR
 When the users click rescan button it should be able to rescan media player with well and correctly.

 ACTUAL BEHAVIOR
 When the users click on rescan media player then the app has stopped and getting crashed.

 HOW TO REPRODUCE
●Install SicMu player on playstore
●open the app and go to setting button
●click advanced settings
●Next,click on rescan media player
●then the app getting crash.
Browser: SicMu player
Device: android 7.0

*RECORDING BUG*
https://youtu.be/U9ybvieg3vs

*LOGCAT*
```FATAL EXCEPTION: main
Process: souch.smp, PID: 23948
java.lang.NullPointerException: Attempt to get length of null array
	at souch.smp.Path.listFiles(Path.java:211)
	at souch.smp.Settings.scanMediaFiles(Settings.java:279)
	at souch.smp.Settings.rescan(Settings.java:245)
	at souch.smp.Settings.onPreferenceClick(Settings.java:236)
	at android.preference.Preference.performClick(Preference.java:990)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1163)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3181)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4008)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3773)
	at android.view.View.dispatchTouchEvent(View.java:8484)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2424)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1768)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:789)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2385)
	at android.view.View.dispatchPoint```

**Comment by souch** [comment]
Thanks for the report. I think this was already fixed on last commit, but I did not released it yet.

**Comment by souch** [comment]
That's strange, i don't think there is a bug here. And I see that all your contributions to others projects are of that kinds. You open similar issues with other account too (e.g. pzdawood). I don't know your purpose, but I am not sure you've got good intentions. I should report it to github.
